### ISSUE TITLE
interface TypedSymbol?

### ISSUE THREAD

**Issue by xied75** [antlr/symtab#6]
We have
```java
public class VariableSymbol extends BaseSymbol implements TypedSymbol
```

And inside BaseSymbol we have
```java
protected Type type;				 // If language statically typed, record type
public Type getType() { return type; }
public void setType(Type type) { this.type = type; }
```

So I'm a bit confused about the role interface **TypedSymbol** plays here. If  BaseSymbol will contain Type, shouldn't it be derived from this interface? Or should we remove Type from BaseSymbol?

From the name, TypedSymbol should be a Symbol, right? @parrt

**Comment by parrt** [comment]
TypedSymbol just means that the symbol has a static type.  Not all symbols have a static type, for example, a package symbol would not have a type.

**Comment by xied75** [comment]
Thanks for answering so fast. But BaseSymbol seems have Type info, why it wasn't a derivative of TypedSymbol?

**Comment by parrt** [comment]
Yes,But mostly because of convenience. There could be other symbols not derived from BaseSymbol the don't happen to include that getType method.
