### ISSUE TITLE
Method overloading?

### ISSUE THREAD

**Issue by xied75** [antlr/symtab#8]
BaseScope.Symbols is using LinkedHashMap<> underneath, which means keys will be unique, so how are we supposed to handle multiple Class constructors or Method Overloading?

I understand that we can replace the data structure with some kind of MultiMap; and Method should be distinguished on the signature (including Return Type, and Parameter Types/Positions). But would like to know your thoughts on this in general, @parrt

**Comment by parrt** [comment]
I didn't implement overloading yet but I would suggest using a Symbol whose key (getName) is a function of the entire signature of method.
